# Covid Data Analysis Assignmnet

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.py as plt

In [2]:
df = pd.read_csv('country_vaccinations.csv')

In [4]:
df = df.fillna(0)

In [5]:
df

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.0,Oxford/AstraZeneca,Government of Afghanistan,https://reliefweb.int/report/afghanistan/afgha...
1,Afghanistan,AFG,2021-02-23,0.0,0.0,0.0,0.0,1367.0,0.00,0.00,0.00,35.0,Oxford/AstraZeneca,Government of Afghanistan,https://reliefweb.int/report/afghanistan/afgha...
2,Afghanistan,AFG,2021-02-24,0.0,0.0,0.0,0.0,1367.0,0.00,0.00,0.00,35.0,Oxford/AstraZeneca,Government of Afghanistan,https://reliefweb.int/report/afghanistan/afgha...
3,Afghanistan,AFG,2021-02-25,0.0,0.0,0.0,0.0,1367.0,0.00,0.00,0.00,35.0,Oxford/AstraZeneca,Government of Afghanistan,https://reliefweb.int/report/afghanistan/afgha...
4,Afghanistan,AFG,2021-02-26,0.0,0.0,0.0,0.0,1367.0,0.00,0.00,0.00,35.0,Oxford/AstraZeneca,Government of Afghanistan,https://reliefweb.int/report/afghanistan/afgha...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15500,Zimbabwe,ZWE,2021-04-30,500342.0,414735.0,85607.0,22745.0,19194.0,3.37,2.79,0.58,1291.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1389675251...
15501,Zimbabwe,ZWE,2021-05-01,520299.0,428135.0,92164.0,19957.0,21171.0,3.50,2.88,0.62,1424.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1389675251...
15502,Zimbabwe,ZWE,2021-05-02,524199.0,430068.0,94131.0,3900.0,19169.0,3.53,2.89,0.63,1290.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1389675251...
15503,Zimbabwe,ZWE,2021-05-03,537516.0,437751.0,99765.0,13317.0,17987.0,3.62,2.95,0.67,1210.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1389675251...
15504,Zimbabwe,ZWE,2021-05-04,559777.0,452191.0,107586.0,22261.0,17977.0,3.77,3.04,0.72,1210.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1389675251...

## Q1. Total number of people vaccinated in Argentina

In [72]:
int(df[df['country'] == 'Argentina'].max()['people_vaccinated'])

7261176

## Q2. Total number of countries in this dataset

In [29]:
no_country = df['country'].unique()

In [31]:
no_country

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Anguilla', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize',
       'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Cambodia', 'Cameroon',
       'Canada', 'Cape Verde', 'Cayman Islands', 'Chile', 'China',
       'Colombia', 'Congo', 'Costa Rica', "Cote d'Ivoire", 'Croatia',
       'Curacao', 'Cyprus', 'Czechia', 'Democratic Republic of Congo',
       'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador',
       'Egypt', 'El Salvador', 'England', 'Equatorial Guinea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Faeroe Islands', 'Falkland Islands',
       'Fiji', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia',
       'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada',
       'Guatemala', 'Guernsey', 'Guinea', 'Guyana', 'Honduras',
       'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran',
       'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica',
       'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kosovo',
       'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho',
       'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mauritania',
       'Mauritius', 'Mexico', 'Moldova', 'Monaco', 'Mongolia',
       'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia',
       'Northern Cyprus', 'Northern Ireland', 'Norway', 'Oman',
       'Pakistan', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay',
       'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania',
       'Russia', 'Rwanda', 'Saint Helena', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa',
       'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Scotland',
       'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia',
       'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka',
       'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Thailand', 'Timor', 'Togo', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Turks and Caicos Islands', 'Uganda',
       'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'United States', 'Uruguay', 'Uzbekistan', 'Venezuela', 'Vietnam',
       'Wales', 'Zambia', 'Zimbabwe'], dtype=object)

In [30]:
len(no_country)

195

## Q3. Maximum number of people vaccinated in a country

In [73]:
def max_vacc (country):
    return int(df[df['country'] == country].max()['people_vaccinated'])

In [74]:
data = []
country = df['country'].unique()
for i in country:
    max_vacc(i)
    data.append([i,max_vacc(i)])

In [75]:
data

[['Afghanistan', 240000],
 ['Albania', 6073],
 ['Algeria', 0],
 ['Andorra', 24182],
 ['Angola', 456349],
 ['Anguilla', 6115],
 ['Antigua and Barbuda', 29754],
 ['Argentina', 7261176],
 ['Armenia', 565],
 ['Aruba', 55159],
 ['Australia', 159294],
 ['Austria', 2460022],
 ['Azerbaijan', 987962],
 ['Bahamas', 25692],
 ['Bahrain', 759975],
 ['Bangladesh', 5819811],
 ['Barbados', 75006],
 ['Belarus', 244000],
 ['Belgium', 3282232],
 ['Belize', 44548],
 ['Bermuda', 32129],
 ['Bhutan', 480818],
 ['Bolivia', 637694],
 ['Bosnia and Herzegovina', 83260],
 ['Botswana', 49882],
 ['Brazil', 30921100],
 ['Brunei', 10715],
 ['Bulgaria', 625922],
 ['Cambodia', 1565292],
 ['Cameroon', 400],
 ['Canada', 13394276],
 ['Cape Verde', 2184],
 ['Cayman Islands', 35774],
 ['Chile', 8232613],
 ['China', 0],
 ['Colombia', 3454250],
 ['Congo', 14297],
 ['Costa Rica', 605099],
 ["Cote d'Ivoire", 183301],
 ['Croatia', 760805],
 ['Curacao', 75555],
 ['Cyprus', 218323],
 ['Czechia', 2399576],
 ['Democratic Republic of Congo', 1700],
 ['Denmark', 1415117],
 ['Djibouti', 10246],
 ['Dominica', 18498],
 ['Dominican Republic', 1319445],
 ['Ecuador', 889218],
 ['Egypt', 660000],
 ['El Salvador', 890109],
 ['England', 29124310],
 ['Equatorial Guinea', 64646],
 ['Estonia', 354238],
 ['Eswatini', 34897],
 ['Ethiopia', 0],
 ['Faeroe Islands', 14458],
 ['Falkland Islands', 2632],
 ['Fiji', 56000],
 ['Finland', 1804953],
 ['France', 16470369],
 ['Gabon', 6895],
 ['Gambia', 20922],
 ['Georgia', 45338],
 ['Germany', 25462944],
 ['Ghana', 849527],
 ['Gibraltar', 37504],
 ['Greece', 2272646],
 ['Greenland', 8900],
 ['Grenada', 12666],
 ['Guatemala', 174152],
 ['Guernsey', 32969],
 ['Guinea', 95911],
 ['Guyana', 124000],
 ['Honduras', 55000],
 ['Hong Kong', 1005425],
 ['Hungary', 4153038],
 ['Iceland', 115447],
 ['India', 129730641],
 ['Indonesia', 12699568],
 ['Iran', 1083138],
 ['Iraq', 298377],
 ['Ireland', 1201373],
 ['Isle of Man', 59206],
 ['Israel', 5414036],
 ['Italy', 15544174],
 ['Jamaica', 135473],
 ['Japan', 2793847],
 ['Jersey', 52850],
 ['Jordan', 805020],
 ['Kazakhstan', 1565681],
 ['Kenya', 853081],
 ['Kosovo', 22096],
 ['Kuwait', 822000],
 ['Kyrgyzstan', 27000],
 ['Laos', 126072],
 ['Latvia', 281137],
 ['Lebanon', 317612],
 ['Lesotho', 16000],
 ['Libya', 750],
 ['Liechtenstein', 8815],
 ['Lithuania', 724952],
 ['Luxembourg', 155897],
 ['Macao', 72879],
 ['Malawi', 296127],
 ['Malaysia', 914663],
 ['Maldives', 298396],
 ['Mali', 49903],
 ['Malta', 241103],
 ['Mauritania', 7038],
 ['Mauritius', 117323],
 ['Mexico', 12984236],
 ['Moldova', 140174],
 ['Monaco', 12758],
 ['Mongolia', 1208913],
 ['Montenegro', 57571],
 ['Montserrat', 1293],
 ['Morocco', 5231766],
 ['Mozambique', 57305],
 ['Myanmar', 1000000],
 ['Namibia', 18837],
 ['Nauru', 700],
 ['Nepal', 2091511],
 ['Netherlands', 4448730],
 ['New Zealand', 217603],
 ['Nicaragua', 135130],
 ['Niger', 1366],
 ['Nigeria', 1246845],
 ['North Macedonia', 74076],
 ['Northern Cyprus', 60642],
 ['Northern Ireland', 950778],
 ['Norway', 1430384],
 ['Oman', 253000],
 ['Pakistan', 2100000],
 ['Palestine', 170109],
 ['Panama', 501055],
 ['Papua New Guinea', 2900],
 ['Paraguay', 131013],
 ['Peru', 1212445],
 ['Philippines', 1786480],
 ['Poland', 9454765],
 ['Portugal', 2644076],
 ['Qatar', 1064294],
 ['Romania', 3449831],
 ['Russia', 12704207],
 ['Rwanda', 350310],
 ['Saint Helena', 3563],
 ['Saint Kitts and Nevis', 12943],
 ['Saint Lucia', 20247],
 ['Saint Vincent and the Grenadines', 0],
 ['Samoa', 0],
 ['San Marino', 21172],
 ['Sao Tome and Principe', 9724],
 ['Saudi Arabia', 0],
 ['Scotland', 2846834],
 ['Senegal', 416956],
 ['Serbia', 2028490],
 ['Seychelles', 68045],
 ['Sierra Leone', 55083],
 ['Singapore', 1364124],
 ['Slovakia', 1164981],
 ['Slovenia', 449475],
 ['Solomon Islands', 4890],
 ['Somalia', 117567],
 ['South Africa', 353181],
 ['South Korea', 3560324],
 ['South Sudan', 947],
 ['Spain', 12686341],
 ['Sri Lanka', 928107],
 ['Sudan', 140227],
 ['Suriname', 41205],
 ['Sweden', 2710287],
 ['Switzerland', 1841984],
 ['Syria', 2500],
 ['Taiwan', 32389],
 ['Thailand', 1167719],
 ['Timor', 2629],
 ['Togo', 160000],
 ['Tonga', 5367],
 ['Trinidad and Tobago', 55259],
 ['Tunisia', 320652],
 ['Turkey', 14264014],
 ['Turks and Caicos Islands', 15039],
 ['Uganda', 341819],
 ['Ukraine', 783810],
 ['United Arab Emirates', 5081853],
 ['United Kingdom', 34795074],
 ['United States', 148562891],
 ['Uruguay', 1203170],
 ['Uzbekistan', 600369],
 ['Venezuela', 250000],
 ['Vietnam', 585539],
 ['Wales', 1873152],
 ['Zambia', 58982],
 ['Zimbabwe', 452191]]

## Q4. Top 5 Countries in terms of number of people vaccinated

In [76]:
data_frame = pd.DataFrame(data, columns =['country', 'people_vaccinated'])

In [77]:

data_frame

         country  people_vaccinated
0    Afghanistan             240000
1        Albania               6073
2        Algeria                  0
3        Andorra              24182
4         Angola             456349
..           ...                ...
190    Venezuela             250000
191      Vietnam             585539
192        Wales            1873152
193       Zambia              58982
194     Zimbabwe             452191

[195 rows x 2 columns]

In [78]:
data_frame.sort_values(by='people_vaccinated', ascending = False).head()

            country  people_vaccinated
187   United States          148562891
78            India          129730641
186  United Kingdom           34795074
25           Brazil           30921100
51          England           29124310